Import('env')
import glob

#Add all source files
objects = glob.glob('*.cpp')

objects = [x for x in objects if x.rfind( "moc_")==-1]


Import('sharedlib')
if sharedlib == 'true':
    objs  = env.SharedObject(objects)
else:
    objs  = env.Object(objects)


Return('objs')
